### PR TITLE
Update metadata for 0.16

### PR DESCRIPTION
**Pull request by dktapps**
This hasn't been thoroughly tested (or at all) but I have corrected all metadata to 0.16 equivalents.

Please, just promise me:
- Use constants, not literal ints >_<
- Use the provided API methods

Thank you.

### CODE REVIEW

**Comment by legoboy0215** [comment]
@jojoe77777 Told you some day we will need to re-write :P

**Comment by SleepSpace9** [comment]
There are two more lines which need an update:

https://github.com/PMPlugins/Slapper/blob/php7/Slapper/src/slapper/Main.php#L382
https://github.com/PMPlugins/Slapper/blob/php7/Slapper/src/slapper/Main.php#L429

**Comment by dktapps** [comment]
@SleepSpace9 Nice one, well spotted. Shall I make another PR or does someone else want to fix it?

**Comment by dktapps** [comment]
This PR should also close #76 and #78

**Comment by jojoe77777** [comment]
> @jojoe77777 Told you some day we will need to re-write :P

I actually started working on that, when I created https://github.com/jojoe77777/Slapper

**Comment by jojoe77777** [comment]
> - Use constants, not literal ints >_<

At the time, I was trying to support Genisys, ImagicalMine, PocketMine, and ClearSky at the same time, and they didn't have the same constant names.

**Comment by dktapps** [comment]
IM: dead
ClearSky: useless, IMv2
Genisys: run by me
PocketMine: run by me

;)

**Comment by HimbeersaftLP** [comment]
> IM: dead

They should have called their organisation "Inactive-to-reactive-to-inactive-again-to-dead"

**Comment by jojoe77777** [comment]
> IM: dead
> ClearSky: useless, IMv2
> Genisys: run by me
> PocketMine: run by me
> 
> ;)

Yes, that's true now

**Comment by ManiakMCPE** [comment]
When will this all be fixed?

**Pull request merged**
