### PR TITLE
Update Slapper to Big Slapper text ! (readme.md)

### PR DESCRIPTION
**Pull request by ghost**
That more beautiful ! :D

### CODE REVIEW

**Comment by Sandertv** [comment]
You can clearly see this is completely messed up in a readme.md

**Comment by ghost** [comment]
Man :( I Have made it with my hand !!

**Comment by ghost** [comment]
for you !

**Comment by Sandertv** [comment]
ASCII Art doesn't work in readme.md, you should have checked it.

**Comment by HimbeersaftLP** [comment]
He could've done it in a codeblock...

**Comment by Sandertv** [comment]
True that ^

**Pull request closed without merging**
