### PR TITLE
Now really fixed #16 on master branch (PHP5)

### LINKED ISSUE #16: All Mobs are Spawning as Slappers
Mobs spawned by spawn eggs are spawning as slappers, which prevents ClearLagg from removing the unwanted mobs.

### PR DESCRIPTION
**Pull request by robske110**
It works!
Here:
[Slapper_v1.2.9.4.phar.zip](https://github.com/PMPlugins/Slapper/files/200780/Slapper_v1.2.9.4.phar.zip)

### CODE REVIEW

**Comment by jojoe77777** [comment]
Slapper 1.3.0 won't take too long. Plus not many people use php 5...

**Comment by robske110** [comment]
Ok, whatever.

**Comment by inxomnyaa** [comment]
@jojoe77777 MANY do still use php5.

**Comment by TheNewHEROBRINEX** [comment]
yes, many people use php5 because many plugins are not yet compatible with php7

**Pull request merged**
